import jsPDF from 'jspdf';
import { ScanResult, ComplianceCertificate } from '../types';

/**
 * Download a JSON object as a file
 */
export const downloadJSON = (data: any, fileName: string) => {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Generate and download a PDF Compliance Attestation
 */
export const exportAttestationPDF = async (result: ScanResult, certificate: ComplianceCertificate) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const primaryColor = [3, 7, 18]; // Slate-950
  const accentColor = [16, 185, 129]; // Emerald-500
  const secondaryColor = [37, 99, 235]; // Blue-600
  const textColor = [31, 41, 55]; // Slate-800
  const lightGray = [241, 245, 249]; // Slate-100

  // Helper for adding horizontal lines
  const horizontalLine = (y: number, color = lightGray) => {
    doc.setDrawColor(color[0], color[1], color[2]);
    doc.line(20, y, 190, y);
  };

  // --- Page 1: Certificate ---
  
  // Header Background
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(0, 0, 210, 60, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.text('CONSENTINEL', 20, 25);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('FORENSIC COMPLIANCE ATTESTATION', 20, 32);

  // Certificate Info (Top Right)
  doc.setFontSize(8);
  doc.text(`CERTIFICATE ID: ${certificate.metadata.certificateId.toUpperCase()}`, 190, 20, { align: 'right' });
  doc.text(`GENERATED: ${new Date(certificate.metadata.generatedAt).toLocaleString()}`, 190, 25, { align: 'right' });
  doc.text(`VALID UNTIL: ${new Date(certificate.metadata.validUntil).toLocaleDateString()}`, 190, 30, { align: 'right' });

  // Certificate Box
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(lightGray[0], lightGray[1], lightGray[2]);
  doc.roundedRect(20, 70, 170, 100, 5, 5, 'FD');

  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('CERTIFICATE OF COMPLIANCE', 105, 95, { align: 'center' });

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  doc.text('This document serves as technical evidence of data transparency', 105, 110, { align: 'center' });
  doc.text('and user consent integrity for the domain:', 105, 117, { align: 'center' });

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
  doc.text(result.url, 105, 132, { align: 'center' });

  // Risk Score Badge
  const riskLevel = certificate.findings.riskLevel;
  const badgeColor = riskLevel === 'CRITICAL' || riskLevel === 'HIGH' ? [239, 68, 68] : 
                    riskLevel === 'MEDIUM' ? [245, 158, 11] : [16, 185, 129];
  
  doc.setFillColor(badgeColor[0], badgeColor[1], badgeColor[2]);
  doc.roundedRect(80, 145, 50, 10, 2, 2, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.text(`${riskLevel} RISK`, 105, 151.5, { align: 'center' });

  // Verification Section
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('VERIFICATION HASHES (SHA-256)', 20, 185);
  
  doc.setFontSize(7);
  doc.setFont('courier', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`SCREENSHOT PRE:  ${certificate.evidence.screenshotHashes.before}`, 20, 192);
  doc.text(`SCREENSHOT POST: ${certificate.evidence.screenshotHashes.after}`, 20, 196);
  doc.text(`REQUEST LOG:     ${certificate.evidence.requestLogHash}`, 20, 200);

  // Footer
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.text('Disclaimer: This report is generated by an automated forensic agent. It represents a snapshot of site behavior at the time of scanning.', 105, 280, { align: 'center' });

  // --- Page 2: Detailed Findings ---
  doc.addPage();
  
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(0, 0, 210, 20, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('DETAILED AUDIT FINDINGS', 20, 13);

  let y = 35;

  // GDPR 2026 Audit Module
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.setFontSize(14);
  doc.text('GDPR 2026 AUDIT MODULE', 20, y);
  y += 10;

  // Parity of Ease
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('1. PARITY OF EASE (EDPB 2026)', 20, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.text(`Status: ${result.gdprAudit?.parityOfEase?.firstLayerRejectVisible ? 'PASS' : 'FAIL'}`, 25, y);
  y += 5;
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(result.gdprAudit?.parityOfEase?.evidence || 'No evidence captured', 25, y, { maxWidth: 160 });
  y += 12;

  // Granularity
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('2. GRANULARITY & PRE-TICKED BOXES (ART. 7)', 20, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.text(`Status: ${result.gdprAudit?.granularity?.preTickedNonEssential ? 'FAIL (Pre-ticked detected)' : 'PASS'}`, 25, y);
  y += 5;
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(result.gdprAudit?.granularity?.evidence || 'No evidence captured', 25, y, { maxWidth: 160 });
  y += 12;

  // Article 13 Transparency
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('3. ARTICLE 13 TRANSPARENCY (VISION AUDIT)', 20, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.text(`Compliance: ${result.gdprAudit?.transparency?.articleCompliance || 'NOT AUDITED'}`, 25, y);
  y += 5;
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(result.gdprAudit?.transparency?.evidence || 'No evidence captured', 25, y, { maxWidth: 160 });
  y += 12;

  // Accessibility (EAA)
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('4. ACCESSIBILITY & EAA COMPLIANCE (POUR)', 20, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.text(`Score: ${result.gdprAudit?.accessibility?.score || 0}/100`, 25, y);
  if (result.gdprAudit?.accessibility?.pourScores) {
    const s = result.gdprAudit.accessibility.pourScores;
    y += 5;
    doc.setFontSize(8);
    doc.text(`Perceivable: ${s.perceivable} | Operable: ${s.operable} | Understandable: ${s.understandable} | Robust: ${s.robust}`, 25, y);
  }
  y += 15;

  // Violation List
  if (certificate.findings.violations.length > 0) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(239, 68, 68);
    doc.text('REGULATORY VIOLATIONS', 20, y);
    y += 10;

    certificate.findings.violations.slice(0, 5).forEach(v => {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
      doc.text(`${v.code}: ${v.article}`, 20, y);
      y += 4;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(textColor[0], textColor[1], textColor[2]);
      doc.text(v.evidence, 25, y, { maxWidth: 160 });
      y += 8;
    });
  }

  // Final Hash & Signature Line
  y = 260;
  horizontalLine(y);
  y += 10;
  doc.setFont('courier', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(`DOCUMENT INTEGRITY HASH: ${certificate.evidence.auditTrailHash}`, 20, y);

  doc.save(`Consentinel_Attestation_${result.id.substring(0, 8)}.pdf`);
};

